// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB4lyiOI8bUh9QbjTAUD6B2fl62U9eu8ZU",
    authDomain: "juantap-db-2dbeb.firebaseapp.com",
    databaseURL: "https://juantap-db-2dbeb-default-rtdb.firebaseio.com",
    projectId: "juantap-db-2dbeb",
    storageBucket: "juantap-db-2dbeb.appspot.com",
    messagingSenderId: "201901470099",
    appId: "1:201901470099:web:bd254aa6d087968438b866",
    measurementId: "G-M02NM47ELK",
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsMR9ccK6F2n4Jnx3NSAOph-LENrm6qg',
    appId: '1:201901470099:android:47cf76cf64cc175638b866',
    messagingSenderId: '201901470099',
    projectId: 'juantap-db-2dbeb',
    databaseURL: 'https://juantap-db-2dbeb-default-rtdb.firebaseio.com',
    storageBucket: 'juantap-db-2dbeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZpEK99wEGHV0nfbBtkqMtcMfmSIRDuI',
    appId: '1:201901470099:ios:c9581f59a09418f238b866',
    messagingSenderId: '201901470099',
    projectId: 'juantap-db-2dbeb',
    databaseURL: 'https://juantap-db-2dbeb-default-rtdb.firebaseio.com',
    storageBucket: 'juantap-db-2dbeb.firebasestorage.app',
    iosBundleId: 'com.example.juantap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4lyiOI8bUh9QbjTAUD6B2fl62U9eu8ZU',
    appId: '1:201901470099:web:d1e452c5142b102338b866',
    messagingSenderId: '201901470099',
    projectId: 'juantap-db-2dbeb',
    authDomain: 'juantap-db-2dbeb.firebaseapp.com',
    databaseURL: 'https://juantap-db-2dbeb-default-rtdb.firebaseio.com',
    storageBucket: 'juantap-db-2dbeb.firebasestorage.app',
    measurementId: 'G-Q4K33NX4ZT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClZpEK99wEGHV0nfbBtkqMtcMfmSIRDuI',
    appId: '1:201901470099:ios:c9581f59a09418f238b866',
    messagingSenderId: '201901470099',
    projectId: 'juantap-db-2dbeb',
    databaseURL: 'https://juantap-db-2dbeb-default-rtdb.firebaseio.com',
    storageBucket: 'juantap-db-2dbeb.firebasestorage.app',
    iosBundleId: 'com.example.juantap',
  );

}